#!/usr/bin/env ruby

require 'bundler/setup'
require_relative 'app/nootify'

def run(argv)
  $stdout.sync = true

  options, args = argv.partition { |x| x.start_with?('-') }

  app = Nootify.new

  options.each do |o|
    if o.start_with?('--interval=')
      app.check_interval = o.split('=')[1].to_i
    end
  end

  case args.first
  when 'login'
    login(args[1])
  when 'check'
    app.sync
  when 'watch'
    app.watch
  else
    print_help
  end
end

def print_help
  puts "Usage: #{$PROGRAM_NAME} login nsec... | login @bluesky"
  puts "       #{$PROGRAM_NAME} check | watch"
  exit 1
end

def login(name)
  app = Nootify.new

  if name&.start_with?('nsec')
    app.login_to_nostr(name)
  elsif name =~ /\A@[^@]+\z/
    app.login_to_bluesky(name)
  elsif name.nil?
    print_help
  else
    puts "Invalid handle: #{name.inspect}"
    exit 1
  end
end

run(ARGV)
